/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosPinturaRouteImport } from './routes/servicos.pintura'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as ServicosPinturaPinturaSlugRouteImport } from './routes/servicos.pintura.$pinturaSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPinturaRoute = ServicosPinturaRouteImport.update({
  id: '/pintura',
  path: '/pintura',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosPinturaPinturaSlugRoute =
  ServicosPinturaPinturaSlugRouteImport.update({
    id: '/$pinturaSlug',
    path: '/$pinturaSlug',
    getParentRoute: () => ServicosPinturaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/pintura'
    | '/servicos/pintura/$pinturaSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/pintura'
    | '/servicos/pintura/$pinturaSlug'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/pintura'
    | '/servicos/pintura/$pinturaSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/pintura': {
      id: '/servicos/pintura'
      path: '/pintura'
      fullPath: '/servicos/pintura'
      preLoaderRoute: typeof ServicosPinturaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/pintura/$pinturaSlug': {
      id: '/servicos/pintura/$pinturaSlug'
      path: '/$pinturaSlug'
      fullPath: '/servicos/pintura/$pinturaSlug'
      preLoaderRoute: typeof ServicosPinturaPinturaSlugRouteImport
      parentRoute: typeof ServicosPinturaRoute
    }
  }
}

interface ServicosPinturaRouteChildren {
  ServicosPinturaPinturaSlugRoute: typeof ServicosPinturaPinturaSlugRoute
}

const ServicosPinturaRouteChildren: ServicosPinturaRouteChildren = {
  ServicosPinturaPinturaSlugRoute: ServicosPinturaPinturaSlugRoute,
}

const ServicosPinturaRouteWithChildren = ServicosPinturaRoute._addFileChildren(
  ServicosPinturaRouteChildren,
)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosPinturaRoute: typeof ServicosPinturaRouteWithChildren
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosPinturaRoute: ServicosPinturaRouteWithChildren,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
