/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosPinturaRouteImport } from './routes/servicos.pintura'
import { Route as ServicosHidraulicaRouteImport } from './routes/servicos.hidraulica'
import { Route as ServicosEletricaRouteImport } from './routes/servicos.eletrica'
import { Route as ServicosDrywallRouteImport } from './routes/servicos.drywall'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as ServicosPinturaIndexRouteImport } from './routes/servicos.pintura.index'
import { Route as ServicosHidraulicaIndexRouteImport } from './routes/servicos.hidraulica.index'
import { Route as ServicosEletricaIndexRouteImport } from './routes/servicos.eletrica.index'
import { Route as ServicosDrywallIndexRouteImport } from './routes/servicos.drywall.index'
import { Route as ServicosPinturaPinturaSlugRouteImport } from './routes/servicos.pintura.$pinturaSlug'
import { Route as ServicosHidraulicaHidraulicaSlugRouteImport } from './routes/servicos.hidraulica.$hidraulicaSlug'
import { Route as ServicosEletricaEletricaSlugRouteImport } from './routes/servicos.eletrica.$eletricaSlug'
import { Route as ServicosDrywallDrywallSlugRouteImport } from './routes/servicos.drywall.$drywallSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPinturaRoute = ServicosPinturaRouteImport.update({
  id: '/pintura',
  path: '/pintura',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosHidraulicaRoute = ServicosHidraulicaRouteImport.update({
  id: '/hidraulica',
  path: '/hidraulica',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosEletricaRoute = ServicosEletricaRouteImport.update({
  id: '/eletrica',
  path: '/eletrica',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosDrywallRoute = ServicosDrywallRouteImport.update({
  id: '/drywall',
  path: '/drywall',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosPinturaIndexRoute = ServicosPinturaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosPinturaRoute,
} as any)
const ServicosHidraulicaIndexRoute = ServicosHidraulicaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosHidraulicaRoute,
} as any)
const ServicosEletricaIndexRoute = ServicosEletricaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosEletricaRoute,
} as any)
const ServicosDrywallIndexRoute = ServicosDrywallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosDrywallRoute,
} as any)
const ServicosPinturaPinturaSlugRoute =
  ServicosPinturaPinturaSlugRouteImport.update({
    id: '/$pinturaSlug',
    path: '/$pinturaSlug',
    getParentRoute: () => ServicosPinturaRoute,
  } as any)
const ServicosHidraulicaHidraulicaSlugRoute =
  ServicosHidraulicaHidraulicaSlugRouteImport.update({
    id: '/$hidraulicaSlug',
    path: '/$hidraulicaSlug',
    getParentRoute: () => ServicosHidraulicaRoute,
  } as any)
const ServicosEletricaEletricaSlugRoute =
  ServicosEletricaEletricaSlugRouteImport.update({
    id: '/$eletricaSlug',
    path: '/$eletricaSlug',
    getParentRoute: () => ServicosEletricaRoute,
  } as any)
const ServicosDrywallDrywallSlugRoute =
  ServicosDrywallDrywallSlugRouteImport.update({
    id: '/$drywallSlug',
    path: '/$drywallSlug',
    getParentRoute: () => ServicosDrywallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/drywall': typeof ServicosDrywallRouteWithChildren
  '/servicos/eletrica': typeof ServicosEletricaRouteWithChildren
  '/servicos/hidraulica': typeof ServicosHidraulicaRouteWithChildren
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/drywall/$drywallSlug': typeof ServicosDrywallDrywallSlugRoute
  '/servicos/eletrica/$eletricaSlug': typeof ServicosEletricaEletricaSlugRoute
  '/servicos/hidraulica/$hidraulicaSlug': typeof ServicosHidraulicaHidraulicaSlugRoute
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
  '/servicos/drywall/': typeof ServicosDrywallIndexRoute
  '/servicos/eletrica/': typeof ServicosEletricaIndexRoute
  '/servicos/hidraulica/': typeof ServicosHidraulicaIndexRoute
  '/servicos/pintura/': typeof ServicosPinturaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/drywall/$drywallSlug': typeof ServicosDrywallDrywallSlugRoute
  '/servicos/eletrica/$eletricaSlug': typeof ServicosEletricaEletricaSlugRoute
  '/servicos/hidraulica/$hidraulicaSlug': typeof ServicosHidraulicaHidraulicaSlugRoute
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
  '/servicos/drywall': typeof ServicosDrywallIndexRoute
  '/servicos/eletrica': typeof ServicosEletricaIndexRoute
  '/servicos/hidraulica': typeof ServicosHidraulicaIndexRoute
  '/servicos/pintura': typeof ServicosPinturaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/drywall': typeof ServicosDrywallRouteWithChildren
  '/servicos/eletrica': typeof ServicosEletricaRouteWithChildren
  '/servicos/hidraulica': typeof ServicosHidraulicaRouteWithChildren
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/drywall/$drywallSlug': typeof ServicosDrywallDrywallSlugRoute
  '/servicos/eletrica/$eletricaSlug': typeof ServicosEletricaEletricaSlugRoute
  '/servicos/hidraulica/$hidraulicaSlug': typeof ServicosHidraulicaHidraulicaSlugRoute
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
  '/servicos/drywall/': typeof ServicosDrywallIndexRoute
  '/servicos/eletrica/': typeof ServicosEletricaIndexRoute
  '/servicos/hidraulica/': typeof ServicosHidraulicaIndexRoute
  '/servicos/pintura/': typeof ServicosPinturaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/drywall'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/pintura'
    | '/servicos/drywall/$drywallSlug'
    | '/servicos/eletrica/$eletricaSlug'
    | '/servicos/hidraulica/$hidraulicaSlug'
    | '/servicos/pintura/$pinturaSlug'
    | '/servicos/drywall/'
    | '/servicos/eletrica/'
    | '/servicos/hidraulica/'
    | '/servicos/pintura/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/drywall/$drywallSlug'
    | '/servicos/eletrica/$eletricaSlug'
    | '/servicos/hidraulica/$hidraulicaSlug'
    | '/servicos/pintura/$pinturaSlug'
    | '/servicos/drywall'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/pintura'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/drywall'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/pintura'
    | '/servicos/drywall/$drywallSlug'
    | '/servicos/eletrica/$eletricaSlug'
    | '/servicos/hidraulica/$hidraulicaSlug'
    | '/servicos/pintura/$pinturaSlug'
    | '/servicos/drywall/'
    | '/servicos/eletrica/'
    | '/servicos/hidraulica/'
    | '/servicos/pintura/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/pintura': {
      id: '/servicos/pintura'
      path: '/pintura'
      fullPath: '/servicos/pintura'
      preLoaderRoute: typeof ServicosPinturaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/hidraulica': {
      id: '/servicos/hidraulica'
      path: '/hidraulica'
      fullPath: '/servicos/hidraulica'
      preLoaderRoute: typeof ServicosHidraulicaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/eletrica': {
      id: '/servicos/eletrica'
      path: '/eletrica'
      fullPath: '/servicos/eletrica'
      preLoaderRoute: typeof ServicosEletricaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/drywall': {
      id: '/servicos/drywall'
      path: '/drywall'
      fullPath: '/servicos/drywall'
      preLoaderRoute: typeof ServicosDrywallRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/pintura/': {
      id: '/servicos/pintura/'
      path: '/'
      fullPath: '/servicos/pintura/'
      preLoaderRoute: typeof ServicosPinturaIndexRouteImport
      parentRoute: typeof ServicosPinturaRoute
    }
    '/servicos/hidraulica/': {
      id: '/servicos/hidraulica/'
      path: '/'
      fullPath: '/servicos/hidraulica/'
      preLoaderRoute: typeof ServicosHidraulicaIndexRouteImport
      parentRoute: typeof ServicosHidraulicaRoute
    }
    '/servicos/eletrica/': {
      id: '/servicos/eletrica/'
      path: '/'
      fullPath: '/servicos/eletrica/'
      preLoaderRoute: typeof ServicosEletricaIndexRouteImport
      parentRoute: typeof ServicosEletricaRoute
    }
    '/servicos/drywall/': {
      id: '/servicos/drywall/'
      path: '/'
      fullPath: '/servicos/drywall/'
      preLoaderRoute: typeof ServicosDrywallIndexRouteImport
      parentRoute: typeof ServicosDrywallRoute
    }
    '/servicos/pintura/$pinturaSlug': {
      id: '/servicos/pintura/$pinturaSlug'
      path: '/$pinturaSlug'
      fullPath: '/servicos/pintura/$pinturaSlug'
      preLoaderRoute: typeof ServicosPinturaPinturaSlugRouteImport
      parentRoute: typeof ServicosPinturaRoute
    }
    '/servicos/hidraulica/$hidraulicaSlug': {
      id: '/servicos/hidraulica/$hidraulicaSlug'
      path: '/$hidraulicaSlug'
      fullPath: '/servicos/hidraulica/$hidraulicaSlug'
      preLoaderRoute: typeof ServicosHidraulicaHidraulicaSlugRouteImport
      parentRoute: typeof ServicosHidraulicaRoute
    }
    '/servicos/eletrica/$eletricaSlug': {
      id: '/servicos/eletrica/$eletricaSlug'
      path: '/$eletricaSlug'
      fullPath: '/servicos/eletrica/$eletricaSlug'
      preLoaderRoute: typeof ServicosEletricaEletricaSlugRouteImport
      parentRoute: typeof ServicosEletricaRoute
    }
    '/servicos/drywall/$drywallSlug': {
      id: '/servicos/drywall/$drywallSlug'
      path: '/$drywallSlug'
      fullPath: '/servicos/drywall/$drywallSlug'
      preLoaderRoute: typeof ServicosDrywallDrywallSlugRouteImport
      parentRoute: typeof ServicosDrywallRoute
    }
  }
}

interface ServicosDrywallRouteChildren {
  ServicosDrywallDrywallSlugRoute: typeof ServicosDrywallDrywallSlugRoute
  ServicosDrywallIndexRoute: typeof ServicosDrywallIndexRoute
}

const ServicosDrywallRouteChildren: ServicosDrywallRouteChildren = {
  ServicosDrywallDrywallSlugRoute: ServicosDrywallDrywallSlugRoute,
  ServicosDrywallIndexRoute: ServicosDrywallIndexRoute,
}

const ServicosDrywallRouteWithChildren = ServicosDrywallRoute._addFileChildren(
  ServicosDrywallRouteChildren,
)

interface ServicosEletricaRouteChildren {
  ServicosEletricaEletricaSlugRoute: typeof ServicosEletricaEletricaSlugRoute
  ServicosEletricaIndexRoute: typeof ServicosEletricaIndexRoute
}

const ServicosEletricaRouteChildren: ServicosEletricaRouteChildren = {
  ServicosEletricaEletricaSlugRoute: ServicosEletricaEletricaSlugRoute,
  ServicosEletricaIndexRoute: ServicosEletricaIndexRoute,
}

const ServicosEletricaRouteWithChildren =
  ServicosEletricaRoute._addFileChildren(ServicosEletricaRouteChildren)

interface ServicosHidraulicaRouteChildren {
  ServicosHidraulicaHidraulicaSlugRoute: typeof ServicosHidraulicaHidraulicaSlugRoute
  ServicosHidraulicaIndexRoute: typeof ServicosHidraulicaIndexRoute
}

const ServicosHidraulicaRouteChildren: ServicosHidraulicaRouteChildren = {
  ServicosHidraulicaHidraulicaSlugRoute: ServicosHidraulicaHidraulicaSlugRoute,
  ServicosHidraulicaIndexRoute: ServicosHidraulicaIndexRoute,
}

const ServicosHidraulicaRouteWithChildren =
  ServicosHidraulicaRoute._addFileChildren(ServicosHidraulicaRouteChildren)

interface ServicosPinturaRouteChildren {
  ServicosPinturaPinturaSlugRoute: typeof ServicosPinturaPinturaSlugRoute
  ServicosPinturaIndexRoute: typeof ServicosPinturaIndexRoute
}

const ServicosPinturaRouteChildren: ServicosPinturaRouteChildren = {
  ServicosPinturaPinturaSlugRoute: ServicosPinturaPinturaSlugRoute,
  ServicosPinturaIndexRoute: ServicosPinturaIndexRoute,
}

const ServicosPinturaRouteWithChildren = ServicosPinturaRoute._addFileChildren(
  ServicosPinturaRouteChildren,
)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosDrywallRoute: typeof ServicosDrywallRouteWithChildren
  ServicosEletricaRoute: typeof ServicosEletricaRouteWithChildren
  ServicosHidraulicaRoute: typeof ServicosHidraulicaRouteWithChildren
  ServicosPinturaRoute: typeof ServicosPinturaRouteWithChildren
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosDrywallRoute: ServicosDrywallRouteWithChildren,
  ServicosEletricaRoute: ServicosEletricaRouteWithChildren,
  ServicosHidraulicaRoute: ServicosHidraulicaRouteWithChildren,
  ServicosPinturaRoute: ServicosPinturaRouteWithChildren,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
