/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSegurancaRouteImport } from './routes/servicos.seguranca'
import { Route as ServicosReformasRouteImport } from './routes/servicos.reformas'
import { Route as ServicosPinturaRouteImport } from './routes/servicos.pintura'
import { Route as ServicosJuntasDilatacaoRouteImport } from './routes/servicos.juntas-dilatacao'
import { Route as ServicosHidraulicaRouteImport } from './routes/servicos.hidraulica'
import { Route as ServicosEletricaRouteImport } from './routes/servicos.eletrica'
import { Route as ServicosDrywallRouteImport } from './routes/servicos.drywall'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as ServicosSegurancaIndexRouteImport } from './routes/servicos.seguranca.index'
import { Route as ServicosReformasIndexRouteImport } from './routes/servicos.reformas.index'
import { Route as ServicosPinturaIndexRouteImport } from './routes/servicos.pintura.index'
import { Route as ServicosJuntasDilatacaoIndexRouteImport } from './routes/servicos.juntas-dilatacao.index'
import { Route as ServicosHidraulicaIndexRouteImport } from './routes/servicos.hidraulica.index'
import { Route as ServicosEletricaIndexRouteImport } from './routes/servicos.eletrica.index'
import { Route as ServicosDrywallIndexRouteImport } from './routes/servicos.drywall.index'
import { Route as ServicosSegurancaSegurancaSlugRouteImport } from './routes/servicos.seguranca.$segurancaSlug'
import { Route as ServicosReformasReformaSlugRouteImport } from './routes/servicos.reformas.$reformaSlug'
import { Route as ServicosPinturaPinturaSlugRouteImport } from './routes/servicos.pintura.$pinturaSlug'
import { Route as ServicosJuntasDilatacaoJuntaSlugRouteImport } from './routes/servicos.juntas-dilatacao.$juntaSlug'
import { Route as ServicosHidraulicaHidraulicaSlugRouteImport } from './routes/servicos.hidraulica.$hidraulicaSlug'
import { Route as ServicosEletricaEletricaSlugRouteImport } from './routes/servicos.eletrica.$eletricaSlug'
import { Route as ServicosDrywallDrywallSlugRouteImport } from './routes/servicos.drywall.$drywallSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSegurancaRoute = ServicosSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosReformasRoute = ServicosReformasRouteImport.update({
  id: '/reformas',
  path: '/reformas',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosPinturaRoute = ServicosPinturaRouteImport.update({
  id: '/pintura',
  path: '/pintura',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosJuntasDilatacaoRoute = ServicosJuntasDilatacaoRouteImport.update({
  id: '/juntas-dilatacao',
  path: '/juntas-dilatacao',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosHidraulicaRoute = ServicosHidraulicaRouteImport.update({
  id: '/hidraulica',
  path: '/hidraulica',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosEletricaRoute = ServicosEletricaRouteImport.update({
  id: '/eletrica',
  path: '/eletrica',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosDrywallRoute = ServicosDrywallRouteImport.update({
  id: '/drywall',
  path: '/drywall',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosSegurancaIndexRoute = ServicosSegurancaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosSegurancaRoute,
} as any)
const ServicosReformasIndexRoute = ServicosReformasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosReformasRoute,
} as any)
const ServicosPinturaIndexRoute = ServicosPinturaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosPinturaRoute,
} as any)
const ServicosJuntasDilatacaoIndexRoute =
  ServicosJuntasDilatacaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServicosJuntasDilatacaoRoute,
  } as any)
const ServicosHidraulicaIndexRoute = ServicosHidraulicaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosHidraulicaRoute,
} as any)
const ServicosEletricaIndexRoute = ServicosEletricaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosEletricaRoute,
} as any)
const ServicosDrywallIndexRoute = ServicosDrywallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicosDrywallRoute,
} as any)
const ServicosSegurancaSegurancaSlugRoute =
  ServicosSegurancaSegurancaSlugRouteImport.update({
    id: '/$segurancaSlug',
    path: '/$segurancaSlug',
    getParentRoute: () => ServicosSegurancaRoute,
  } as any)
const ServicosReformasReformaSlugRoute =
  ServicosReformasReformaSlugRouteImport.update({
    id: '/$reformaSlug',
    path: '/$reformaSlug',
    getParentRoute: () => ServicosReformasRoute,
  } as any)
const ServicosPinturaPinturaSlugRoute =
  ServicosPinturaPinturaSlugRouteImport.update({
    id: '/$pinturaSlug',
    path: '/$pinturaSlug',
    getParentRoute: () => ServicosPinturaRoute,
  } as any)
const ServicosJuntasDilatacaoJuntaSlugRoute =
  ServicosJuntasDilatacaoJuntaSlugRouteImport.update({
    id: '/$juntaSlug',
    path: '/$juntaSlug',
    getParentRoute: () => ServicosJuntasDilatacaoRoute,
  } as any)
const ServicosHidraulicaHidraulicaSlugRoute =
  ServicosHidraulicaHidraulicaSlugRouteImport.update({
    id: '/$hidraulicaSlug',
    path: '/$hidraulicaSlug',
    getParentRoute: () => ServicosHidraulicaRoute,
  } as any)
const ServicosEletricaEletricaSlugRoute =
  ServicosEletricaEletricaSlugRouteImport.update({
    id: '/$eletricaSlug',
    path: '/$eletricaSlug',
    getParentRoute: () => ServicosEletricaRoute,
  } as any)
const ServicosDrywallDrywallSlugRoute =
  ServicosDrywallDrywallSlugRouteImport.update({
    id: '/$drywallSlug',
    path: '/$drywallSlug',
    getParentRoute: () => ServicosDrywallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/drywall': typeof ServicosDrywallRouteWithChildren
  '/servicos/eletrica': typeof ServicosEletricaRouteWithChildren
  '/servicos/hidraulica': typeof ServicosHidraulicaRouteWithChildren
  '/servicos/juntas-dilatacao': typeof ServicosJuntasDilatacaoRouteWithChildren
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/reformas': typeof ServicosReformasRouteWithChildren
  '/servicos/seguranca': typeof ServicosSegurancaRouteWithChildren
  '/servicos/': typeof ServicosIndexRoute
  '/servicos/drywall/$drywallSlug': typeof ServicosDrywallDrywallSlugRoute
  '/servicos/eletrica/$eletricaSlug': typeof ServicosEletricaEletricaSlugRoute
  '/servicos/hidraulica/$hidraulicaSlug': typeof ServicosHidraulicaHidraulicaSlugRoute
  '/servicos/juntas-dilatacao/$juntaSlug': typeof ServicosJuntasDilatacaoJuntaSlugRoute
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
  '/servicos/reformas/$reformaSlug': typeof ServicosReformasReformaSlugRoute
  '/servicos/seguranca/$segurancaSlug': typeof ServicosSegurancaSegurancaSlugRoute
  '/servicos/drywall/': typeof ServicosDrywallIndexRoute
  '/servicos/eletrica/': typeof ServicosEletricaIndexRoute
  '/servicos/hidraulica/': typeof ServicosHidraulicaIndexRoute
  '/servicos/juntas-dilatacao/': typeof ServicosJuntasDilatacaoIndexRoute
  '/servicos/pintura/': typeof ServicosPinturaIndexRoute
  '/servicos/reformas/': typeof ServicosReformasIndexRoute
  '/servicos/seguranca/': typeof ServicosSegurancaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos': typeof ServicosIndexRoute
  '/servicos/drywall/$drywallSlug': typeof ServicosDrywallDrywallSlugRoute
  '/servicos/eletrica/$eletricaSlug': typeof ServicosEletricaEletricaSlugRoute
  '/servicos/hidraulica/$hidraulicaSlug': typeof ServicosHidraulicaHidraulicaSlugRoute
  '/servicos/juntas-dilatacao/$juntaSlug': typeof ServicosJuntasDilatacaoJuntaSlugRoute
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
  '/servicos/reformas/$reformaSlug': typeof ServicosReformasReformaSlugRoute
  '/servicos/seguranca/$segurancaSlug': typeof ServicosSegurancaSegurancaSlugRoute
  '/servicos/drywall': typeof ServicosDrywallIndexRoute
  '/servicos/eletrica': typeof ServicosEletricaIndexRoute
  '/servicos/hidraulica': typeof ServicosHidraulicaIndexRoute
  '/servicos/juntas-dilatacao': typeof ServicosJuntasDilatacaoIndexRoute
  '/servicos/pintura': typeof ServicosPinturaIndexRoute
  '/servicos/reformas': typeof ServicosReformasIndexRoute
  '/servicos/seguranca': typeof ServicosSegurancaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/servicos/drywall': typeof ServicosDrywallRouteWithChildren
  '/servicos/eletrica': typeof ServicosEletricaRouteWithChildren
  '/servicos/hidraulica': typeof ServicosHidraulicaRouteWithChildren
  '/servicos/juntas-dilatacao': typeof ServicosJuntasDilatacaoRouteWithChildren
  '/servicos/pintura': typeof ServicosPinturaRouteWithChildren
  '/servicos/reformas': typeof ServicosReformasRouteWithChildren
  '/servicos/seguranca': typeof ServicosSegurancaRouteWithChildren
  '/servicos/': typeof ServicosIndexRoute
  '/servicos/drywall/$drywallSlug': typeof ServicosDrywallDrywallSlugRoute
  '/servicos/eletrica/$eletricaSlug': typeof ServicosEletricaEletricaSlugRoute
  '/servicos/hidraulica/$hidraulicaSlug': typeof ServicosHidraulicaHidraulicaSlugRoute
  '/servicos/juntas-dilatacao/$juntaSlug': typeof ServicosJuntasDilatacaoJuntaSlugRoute
  '/servicos/pintura/$pinturaSlug': typeof ServicosPinturaPinturaSlugRoute
  '/servicos/reformas/$reformaSlug': typeof ServicosReformasReformaSlugRoute
  '/servicos/seguranca/$segurancaSlug': typeof ServicosSegurancaSegurancaSlugRoute
  '/servicos/drywall/': typeof ServicosDrywallIndexRoute
  '/servicos/eletrica/': typeof ServicosEletricaIndexRoute
  '/servicos/hidraulica/': typeof ServicosHidraulicaIndexRoute
  '/servicos/juntas-dilatacao/': typeof ServicosJuntasDilatacaoIndexRoute
  '/servicos/pintura/': typeof ServicosPinturaIndexRoute
  '/servicos/reformas/': typeof ServicosReformasIndexRoute
  '/servicos/seguranca/': typeof ServicosSegurancaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/drywall'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/juntas-dilatacao'
    | '/servicos/pintura'
    | '/servicos/reformas'
    | '/servicos/seguranca'
    | '/servicos/'
    | '/servicos/drywall/$drywallSlug'
    | '/servicos/eletrica/$eletricaSlug'
    | '/servicos/hidraulica/$hidraulicaSlug'
    | '/servicos/juntas-dilatacao/$juntaSlug'
    | '/servicos/pintura/$pinturaSlug'
    | '/servicos/reformas/$reformaSlug'
    | '/servicos/seguranca/$segurancaSlug'
    | '/servicos/drywall/'
    | '/servicos/eletrica/'
    | '/servicos/hidraulica/'
    | '/servicos/juntas-dilatacao/'
    | '/servicos/pintura/'
    | '/servicos/reformas/'
    | '/servicos/seguranca/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos'
    | '/servicos/drywall/$drywallSlug'
    | '/servicos/eletrica/$eletricaSlug'
    | '/servicos/hidraulica/$hidraulicaSlug'
    | '/servicos/juntas-dilatacao/$juntaSlug'
    | '/servicos/pintura/$pinturaSlug'
    | '/servicos/reformas/$reformaSlug'
    | '/servicos/seguranca/$segurancaSlug'
    | '/servicos/drywall'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/juntas-dilatacao'
    | '/servicos/pintura'
    | '/servicos/reformas'
    | '/servicos/seguranca'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/servicos'
    | '/sitemap.xml'
    | '/servicos/$slug'
    | '/servicos/drywall'
    | '/servicos/eletrica'
    | '/servicos/hidraulica'
    | '/servicos/juntas-dilatacao'
    | '/servicos/pintura'
    | '/servicos/reformas'
    | '/servicos/seguranca'
    | '/servicos/'
    | '/servicos/drywall/$drywallSlug'
    | '/servicos/eletrica/$eletricaSlug'
    | '/servicos/hidraulica/$hidraulicaSlug'
    | '/servicos/juntas-dilatacao/$juntaSlug'
    | '/servicos/pintura/$pinturaSlug'
    | '/servicos/reformas/$reformaSlug'
    | '/servicos/seguranca/$segurancaSlug'
    | '/servicos/drywall/'
    | '/servicos/eletrica/'
    | '/servicos/hidraulica/'
    | '/servicos/juntas-dilatacao/'
    | '/servicos/pintura/'
    | '/servicos/reformas/'
    | '/servicos/seguranca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/seguranca': {
      id: '/servicos/seguranca'
      path: '/seguranca'
      fullPath: '/servicos/seguranca'
      preLoaderRoute: typeof ServicosSegurancaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/reformas': {
      id: '/servicos/reformas'
      path: '/reformas'
      fullPath: '/servicos/reformas'
      preLoaderRoute: typeof ServicosReformasRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/pintura': {
      id: '/servicos/pintura'
      path: '/pintura'
      fullPath: '/servicos/pintura'
      preLoaderRoute: typeof ServicosPinturaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/juntas-dilatacao': {
      id: '/servicos/juntas-dilatacao'
      path: '/juntas-dilatacao'
      fullPath: '/servicos/juntas-dilatacao'
      preLoaderRoute: typeof ServicosJuntasDilatacaoRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/hidraulica': {
      id: '/servicos/hidraulica'
      path: '/hidraulica'
      fullPath: '/servicos/hidraulica'
      preLoaderRoute: typeof ServicosHidraulicaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/eletrica': {
      id: '/servicos/eletrica'
      path: '/eletrica'
      fullPath: '/servicos/eletrica'
      preLoaderRoute: typeof ServicosEletricaRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/drywall': {
      id: '/servicos/drywall'
      path: '/drywall'
      fullPath: '/servicos/drywall'
      preLoaderRoute: typeof ServicosDrywallRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/seguranca/': {
      id: '/servicos/seguranca/'
      path: '/'
      fullPath: '/servicos/seguranca/'
      preLoaderRoute: typeof ServicosSegurancaIndexRouteImport
      parentRoute: typeof ServicosSegurancaRoute
    }
    '/servicos/reformas/': {
      id: '/servicos/reformas/'
      path: '/'
      fullPath: '/servicos/reformas/'
      preLoaderRoute: typeof ServicosReformasIndexRouteImport
      parentRoute: typeof ServicosReformasRoute
    }
    '/servicos/pintura/': {
      id: '/servicos/pintura/'
      path: '/'
      fullPath: '/servicos/pintura/'
      preLoaderRoute: typeof ServicosPinturaIndexRouteImport
      parentRoute: typeof ServicosPinturaRoute
    }
    '/servicos/juntas-dilatacao/': {
      id: '/servicos/juntas-dilatacao/'
      path: '/'
      fullPath: '/servicos/juntas-dilatacao/'
      preLoaderRoute: typeof ServicosJuntasDilatacaoIndexRouteImport
      parentRoute: typeof ServicosJuntasDilatacaoRoute
    }
    '/servicos/hidraulica/': {
      id: '/servicos/hidraulica/'
      path: '/'
      fullPath: '/servicos/hidraulica/'
      preLoaderRoute: typeof ServicosHidraulicaIndexRouteImport
      parentRoute: typeof ServicosHidraulicaRoute
    }
    '/servicos/eletrica/': {
      id: '/servicos/eletrica/'
      path: '/'
      fullPath: '/servicos/eletrica/'
      preLoaderRoute: typeof ServicosEletricaIndexRouteImport
      parentRoute: typeof ServicosEletricaRoute
    }
    '/servicos/drywall/': {
      id: '/servicos/drywall/'
      path: '/'
      fullPath: '/servicos/drywall/'
      preLoaderRoute: typeof ServicosDrywallIndexRouteImport
      parentRoute: typeof ServicosDrywallRoute
    }
    '/servicos/seguranca/$segurancaSlug': {
      id: '/servicos/seguranca/$segurancaSlug'
      path: '/$segurancaSlug'
      fullPath: '/servicos/seguranca/$segurancaSlug'
      preLoaderRoute: typeof ServicosSegurancaSegurancaSlugRouteImport
      parentRoute: typeof ServicosSegurancaRoute
    }
    '/servicos/reformas/$reformaSlug': {
      id: '/servicos/reformas/$reformaSlug'
      path: '/$reformaSlug'
      fullPath: '/servicos/reformas/$reformaSlug'
      preLoaderRoute: typeof ServicosReformasReformaSlugRouteImport
      parentRoute: typeof ServicosReformasRoute
    }
    '/servicos/pintura/$pinturaSlug': {
      id: '/servicos/pintura/$pinturaSlug'
      path: '/$pinturaSlug'
      fullPath: '/servicos/pintura/$pinturaSlug'
      preLoaderRoute: typeof ServicosPinturaPinturaSlugRouteImport
      parentRoute: typeof ServicosPinturaRoute
    }
    '/servicos/juntas-dilatacao/$juntaSlug': {
      id: '/servicos/juntas-dilatacao/$juntaSlug'
      path: '/$juntaSlug'
      fullPath: '/servicos/juntas-dilatacao/$juntaSlug'
      preLoaderRoute: typeof ServicosJuntasDilatacaoJuntaSlugRouteImport
      parentRoute: typeof ServicosJuntasDilatacaoRoute
    }
    '/servicos/hidraulica/$hidraulicaSlug': {
      id: '/servicos/hidraulica/$hidraulicaSlug'
      path: '/$hidraulicaSlug'
      fullPath: '/servicos/hidraulica/$hidraulicaSlug'
      preLoaderRoute: typeof ServicosHidraulicaHidraulicaSlugRouteImport
      parentRoute: typeof ServicosHidraulicaRoute
    }
    '/servicos/eletrica/$eletricaSlug': {
      id: '/servicos/eletrica/$eletricaSlug'
      path: '/$eletricaSlug'
      fullPath: '/servicos/eletrica/$eletricaSlug'
      preLoaderRoute: typeof ServicosEletricaEletricaSlugRouteImport
      parentRoute: typeof ServicosEletricaRoute
    }
    '/servicos/drywall/$drywallSlug': {
      id: '/servicos/drywall/$drywallSlug'
      path: '/$drywallSlug'
      fullPath: '/servicos/drywall/$drywallSlug'
      preLoaderRoute: typeof ServicosDrywallDrywallSlugRouteImport
      parentRoute: typeof ServicosDrywallRoute
    }
  }
}

interface ServicosDrywallRouteChildren {
  ServicosDrywallDrywallSlugRoute: typeof ServicosDrywallDrywallSlugRoute
  ServicosDrywallIndexRoute: typeof ServicosDrywallIndexRoute
}

const ServicosDrywallRouteChildren: ServicosDrywallRouteChildren = {
  ServicosDrywallDrywallSlugRoute: ServicosDrywallDrywallSlugRoute,
  ServicosDrywallIndexRoute: ServicosDrywallIndexRoute,
}

const ServicosDrywallRouteWithChildren = ServicosDrywallRoute._addFileChildren(
  ServicosDrywallRouteChildren,
)

interface ServicosEletricaRouteChildren {
  ServicosEletricaEletricaSlugRoute: typeof ServicosEletricaEletricaSlugRoute
  ServicosEletricaIndexRoute: typeof ServicosEletricaIndexRoute
}

const ServicosEletricaRouteChildren: ServicosEletricaRouteChildren = {
  ServicosEletricaEletricaSlugRoute: ServicosEletricaEletricaSlugRoute,
  ServicosEletricaIndexRoute: ServicosEletricaIndexRoute,
}

const ServicosEletricaRouteWithChildren =
  ServicosEletricaRoute._addFileChildren(ServicosEletricaRouteChildren)

interface ServicosHidraulicaRouteChildren {
  ServicosHidraulicaHidraulicaSlugRoute: typeof ServicosHidraulicaHidraulicaSlugRoute
  ServicosHidraulicaIndexRoute: typeof ServicosHidraulicaIndexRoute
}

const ServicosHidraulicaRouteChildren: ServicosHidraulicaRouteChildren = {
  ServicosHidraulicaHidraulicaSlugRoute: ServicosHidraulicaHidraulicaSlugRoute,
  ServicosHidraulicaIndexRoute: ServicosHidraulicaIndexRoute,
}

const ServicosHidraulicaRouteWithChildren =
  ServicosHidraulicaRoute._addFileChildren(ServicosHidraulicaRouteChildren)

interface ServicosJuntasDilatacaoRouteChildren {
  ServicosJuntasDilatacaoJuntaSlugRoute: typeof ServicosJuntasDilatacaoJuntaSlugRoute
  ServicosJuntasDilatacaoIndexRoute: typeof ServicosJuntasDilatacaoIndexRoute
}

const ServicosJuntasDilatacaoRouteChildren: ServicosJuntasDilatacaoRouteChildren =
  {
    ServicosJuntasDilatacaoJuntaSlugRoute:
      ServicosJuntasDilatacaoJuntaSlugRoute,
    ServicosJuntasDilatacaoIndexRoute: ServicosJuntasDilatacaoIndexRoute,
  }

const ServicosJuntasDilatacaoRouteWithChildren =
  ServicosJuntasDilatacaoRoute._addFileChildren(
    ServicosJuntasDilatacaoRouteChildren,
  )

interface ServicosPinturaRouteChildren {
  ServicosPinturaPinturaSlugRoute: typeof ServicosPinturaPinturaSlugRoute
  ServicosPinturaIndexRoute: typeof ServicosPinturaIndexRoute
}

const ServicosPinturaRouteChildren: ServicosPinturaRouteChildren = {
  ServicosPinturaPinturaSlugRoute: ServicosPinturaPinturaSlugRoute,
  ServicosPinturaIndexRoute: ServicosPinturaIndexRoute,
}

const ServicosPinturaRouteWithChildren = ServicosPinturaRoute._addFileChildren(
  ServicosPinturaRouteChildren,
)

interface ServicosReformasRouteChildren {
  ServicosReformasReformaSlugRoute: typeof ServicosReformasReformaSlugRoute
  ServicosReformasIndexRoute: typeof ServicosReformasIndexRoute
}

const ServicosReformasRouteChildren: ServicosReformasRouteChildren = {
  ServicosReformasReformaSlugRoute: ServicosReformasReformaSlugRoute,
  ServicosReformasIndexRoute: ServicosReformasIndexRoute,
}

const ServicosReformasRouteWithChildren =
  ServicosReformasRoute._addFileChildren(ServicosReformasRouteChildren)

interface ServicosSegurancaRouteChildren {
  ServicosSegurancaSegurancaSlugRoute: typeof ServicosSegurancaSegurancaSlugRoute
  ServicosSegurancaIndexRoute: typeof ServicosSegurancaIndexRoute
}

const ServicosSegurancaRouteChildren: ServicosSegurancaRouteChildren = {
  ServicosSegurancaSegurancaSlugRoute: ServicosSegurancaSegurancaSlugRoute,
  ServicosSegurancaIndexRoute: ServicosSegurancaIndexRoute,
}

const ServicosSegurancaRouteWithChildren =
  ServicosSegurancaRoute._addFileChildren(ServicosSegurancaRouteChildren)

interface ServicosRouteChildren {
  ServicosSlugRoute: typeof ServicosSlugRoute
  ServicosDrywallRoute: typeof ServicosDrywallRouteWithChildren
  ServicosEletricaRoute: typeof ServicosEletricaRouteWithChildren
  ServicosHidraulicaRoute: typeof ServicosHidraulicaRouteWithChildren
  ServicosJuntasDilatacaoRoute: typeof ServicosJuntasDilatacaoRouteWithChildren
  ServicosPinturaRoute: typeof ServicosPinturaRouteWithChildren
  ServicosReformasRoute: typeof ServicosReformasRouteWithChildren
  ServicosSegurancaRoute: typeof ServicosSegurancaRouteWithChildren
  ServicosIndexRoute: typeof ServicosIndexRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosSlugRoute: ServicosSlugRoute,
  ServicosDrywallRoute: ServicosDrywallRouteWithChildren,
  ServicosEletricaRoute: ServicosEletricaRouteWithChildren,
  ServicosHidraulicaRoute: ServicosHidraulicaRouteWithChildren,
  ServicosJuntasDilatacaoRoute: ServicosJuntasDilatacaoRouteWithChildren,
  ServicosPinturaRoute: ServicosPinturaRouteWithChildren,
  ServicosReformasRoute: ServicosReformasRouteWithChildren,
  ServicosSegurancaRoute: ServicosSegurancaRouteWithChildren,
  ServicosIndexRoute: ServicosIndexRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
